// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "flutter_barcode_sdk_ios",
    platforms: [
        .iOS("13.0")
    ],
    products: [
        .library(name: "flutter-barcode-sdk-ios", targets: ["flutter_barcode_sdk_ios"])
    ],
    dependencies: [
        // Local package generated by the Flutter tool (Flutter 3.44+) that
        // exposes the Flutter.framework headers to SPM-built plugins.
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
        // Dynamsoft Barcode Reader Bundle (xcframeworks) for iOS.
        .package(
            url: "https://github.com/Dynamsoft/barcode-reader-spm",
            from: "11.6.1000"
        ),
    ],
    targets: [
        .target(
            name: "flutter_barcode_sdk_ios",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                .product(
                    name: "DynamsoftBarcodeReaderBundle",
                    package: "barcode-reader-spm"
                ),
            ]
        )
    ]
)
