name: flutter_barcode_sdk_platform_interface
resolution: workspace
description: A common platform interface for the flutter_barcode_sdk plugin.
version: 1.0.0
repository: https://github.com/yushulx/flutter_barcode_sdk_platform_interface

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
