name: flutter_barcode_sdk
resolution: workspace
description: The only Flutter barcode SDK for Android, iOS, Web, Windows, Linux, macOS. Empower developers to build 1D/2D barcode reader and barcode scanner.
version: 5.1.0
homepage: https://www.dynamsoft.com/barcode-reader/overview/
repository: https://github.com/yushulx/flutter_barcode_sdk

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  # Platform interface
  flutter_barcode_sdk_platform_interface: ^1.0.0

  # Endorsed platform implementations
  flutter_barcode_sdk_android: ^1.0.0
  flutter_barcode_sdk_macos: ^1.0.0
  flutter_barcode_sdk_ios: ^1.0.0
  flutter_barcode_sdk_windows: ^1.0.0
  flutter_barcode_sdk_linux: ^1.0.0
  flutter_barcode_sdk_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_barcode_sdk_android
      macos:
        default_package: flutter_barcode_sdk_macos
      ios:
        default_package: flutter_barcode_sdk_ios
      windows:
        default_package: flutter_barcode_sdk_windows
      linux:
        default_package: flutter_barcode_sdk_linux
      web:
        default_package: flutter_barcode_sdk_web