// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "flutter_barcode_sdk_macos",
    platforms: [
        .macOS("12.0")
    ],
    products: [
        .library(name: "flutter-barcode-sdk-macos", targets: ["flutter_barcode_sdk_macos"])
    ],
    dependencies: [
        // Local package generated by the Flutter tool (Flutter 3.44+) that
        // exposes the FlutterMacOS.framework headers to SPM-built plugins.
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        .target(
            name: "flutter_barcode_sdk_macos",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
            ],
            // Public headers live in include/<module_name>/ so the generated
            // plugin registrant can
            // `#import <flutter_barcode_sdk_macos/FlutterBarcodeSdkPlugin.h>`.
            cSettings: [
                .headerSearchPath("include/flutter_barcode_sdk_macos"),
                // Dynamsoft desktop SDK headers, vendored in the package at Libraries/.
                .headerSearchPath("../../Libraries"),
            ],
            linkerSettings: [
                // Dynamsoft desktop SDK dylibs, vendored in the package
                // at Libraries/.
                //
                // NOTE: Swift Package Manager provides no portable way to add
                // a library search path (-L) for vendored dylibs, and Dynamsoft
                // does not ship macOS xcframeworks or an SPM package, so the
                // app target must make Libraries/ discoverable to the
                // linker (e.g. LIBRARY_SEARCH_PATHS) and embed the dylibs.
                // CocoaPods remains the fully supported integration path on
                // macOS — see flutter_barcode_sdk_macos.podspec.
                .linkedLibrary("DynamsoftCore"),
                .linkedLibrary("DynamsoftImageProcessing"),
                .linkedLibrary("DynamsoftLicense"),
                .linkedLibrary("DynamsoftBarcodeReader"),
                .linkedLibrary("DynamsoftCaptureVisionRouter"),
                .linkedLibrary("DynamsoftUtility"),
                .linkedLibrary("DynamsoftNeuralNetwork"),
                .linkedLibrary("DynamicPdf"),
            ]
        )
    ],
    // Matches CLANG_CXX_LANGUAGE_STANDARD=c++17 in the podspec; the ObjC++
    // bridge uses C++17 APIs from the Dynamsoft SDK.
    cxxLanguageStandard: .cxx17
)
