name: flutter_barcode_sdk_linux
resolution: workspace
description: Linux platform implementation of flutter_barcode_sdk.
version: 1.0.1
repository: https://github.com/yushulx/flutter_barcode_sdk_linux

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_barcode_sdk
    platforms:
      linux:
        pluginClass: FlutterBarcodeSdkPlugin
