name: flutter_barcode_sdk_android_example
resolution: workspace
description: Example app for flutter_barcode_sdk_android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_barcode_sdk: ^5.0.0
  camera: ^0.11.1
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/default.png
    - images/qr-test.png
